# --- Video Player Settings ---
loop-file=inf                           # Infinitely loop current playing video

# --- Core Performance ---
profile=gpu-hq                          # Improved scaling, color, and de-banding on modern GPUs
vo=gpu-next                             # Superior HDR-to-SDR tone mapping, better color management, and more efficient rendering
gpu-api=d3d11                           # Improves performance, better hardware acceleration, and enhances stability
hwdec=d3d11va                           # Provides direct GPU decoding with no RAM copying (zero-copy)
gpu-context=d3d11                       # Matches API for best stability